-----------------------------------------------------------
--SILVER
-----------------------------------------------------------

-----------------------------------------------------------
--CREACION DE PROCESOS DE CARGA A LAS TABLAS STG
-----------------------------------------------------------
USE DATABASE AW_PIPELINE;
USE SCHEMA STAGING;


-----------------------------------------------------------
--STG_CUSTOMER
-----------------------------------------------------------

CREATE OR REPLACE PROCEDURE STAGING.SP_LOAD_STG_CUSTOMER()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
TRUNCATE TABLE STAGING.STG_CUSTOMER;
    INSERT INTO STAGING.STG_CUSTOMER(CUSTOMERID, PERSONID, STOREID, TERRITORYID, CREATED_DATE)
    SELECT TRY_CAST(CUSTOMERID AS INTEGER), TRY_CAST(PERSONID AS INTEGER), TRY_CAST(STOREID AS INTEGER), TRY_CAST(TERRITORYID AS INTEGER), TO_CHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD HH24:MI:SS') FROM RAW.CUSTOMER;
COMMIT;
END;

-----------------------------------------------------------
--STG_PERSON
-----------------------------------------------------------

CREATE OR REPLACE PROCEDURE STAGING.SP_LOAD_STG_PERSON()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
TRUNCATE TABLE STAGING.STG_PERSON;
    INSERT INTO STAGING.STG_PERSON(BUSINESSENTITYID, PERSONTYPE, TITLE, FIRSTNAME, MIDDLENAME, LASTNAME, CREATED_DATE)
    SELECT TRY_CAST(BUSINESSENTITYID AS INTEGER), PERSONTYPE, TITLE, FIRSTNAME, MIDDLENAME, LASTNAME, TO_CHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD HH24:MI:SS') FROM RAW.PERSON;
COMMIT;
END;

-----------------------------------------------------------
--STG_STORES
-----------------------------------------------------------

CREATE OR REPLACE PROCEDURE STAGING.SP_LOAD_STG_STORES()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
TRUNCATE TABLE STAGING.STG_STORE;
    INSERT INTO STAGING.STG_STORE(BUSINESSENTITYID, NAME, CREATED_DATE)
    SELECT TRY_CAST(BUSINESSENTITYID AS INTEGER), NAME, TO_CHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD HH24:MI:SS') FROM RAW.STORE;
COMMIT;
END;

-----------------------------------------------------------
--STG_SALASTERRITORY
-----------------------------------------------------------

CREATE OR REPLACE PROCEDURE STAGING.SP_LOAD_STG_SALASTERRITORY()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
TRUNCATE TABLE STAGING.STG_SALESTERRITORY;
    INSERT INTO STAGING.STG_SALESTERRITORY(TERRITORYID, NAME, COUNTRYREGIONCODE, GROUP_, SALESYTD, SALESLASTYEAR, CREATED_DATE)
    SELECT TRY_CAST( TERRITORYID AS INTEGER), NAME, COUNTRYREGIONCODE, GROUP_, TRY_CAST(SALESYTD AS INTEGER), TRY_CAST(SALESLASTYEAR AS INTEGER), TO_CHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD HH24:MI:SS') FROM RAW.SALESTERRITORY;
COMMIT;
END;

-----------------------------------------------------------
--STG_PRODUCT
-----------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_LOAD_STG_PRODUCT()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
MERGE INTO STAGING.STG_PRODUCT DM
USING (
    SELECT TRY_CAST(P.PRODUCTID AS INTEGER) AS PRODUCTID, P.NAME, P.PRODUCTNUMBER, P.COLOR,
           TRY_CAST(P.LISTPRICE AS FLOAT) AS LISTPRICE, TRY_CAST(P.STANDARDCOST AS FLOAT) AS STANDARCOST,
           SUB.NAME AS SUBCATEGORYNAME, CAT.NAME AS CATEGORYNAME
    FROM RAW.PRODUCT P
    LEFT JOIN RAW.PRODUCTSUBCATEGORY SUB ON P.PRODUCTSUBCATEGORYID = SUB.PRODUCTSUBCATEGORYID
    LEFT JOIN RAW.PRODUCTCATEGORY CAT ON SUB.PRODUCTCATEGORYID = CAT.PRODUCTCATEGORYID
) AUX
ON DM.PRODUCTID = AUX.PRODUCTID
WHEN MATCHED AND (
        DM.NAME               != AUX.NAME
        OR DM.COLOR         != AUX.COLOR
        OR DM.PRODUCT_NUMBER     != AUX.PRODUCTNUMBER
     OR DM.LISTPRICE           != AUX.LISTPRICE
     OR DM.STANDARCOST         != AUX.STANDARCOST
     OR DM.SUBCATEGORYNAME     != AUX.SUBCATEGORYNAME
     OR DM.CATEGORYNAME        != AUX.CATEGORYNAME
) THEN UPDATE SET
    DM.NAME = AUX.NAME, DM.LISTPRICE = AUX.LISTPRICE, DM.STANDARCOST = AUX.STANDARCOST,
    DM.SUBCATEGORYNAME = AUX.SUBCATEGORYNAME, DM.CATEGORYNAME = AUX.CATEGORYNAME
WHEN NOT MATCHED THEN INSERT (PRODUCTID, NAME, PRODUCT_NUMBER, COLOR, LISTPRICE, STANDARCOST, SUBCATEGORYNAME, CATEGORYNAME)
     VALUES (AUX.PRODUCTID, AUX.NAME, AUX.PRODUCTNUMBER, AUX.COLOR, AUX.LISTPRICE, AUX.STANDARCOST, AUX.SUBCATEGORYNAME, AUX.CATEGORYNAME);


    COMMIT;

END;
$$
;
-----------------------------------------------------------
--STG_SALESORDERHEADER
-----------------------------------------------------------

CREATE OR REPLACE PROCEDURE STAGING.SP_LOAD_STG_SALESORDERHEADER()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
TRUNCATE TABLE STAGING.STG_SALESORDERHEADER;
    INSERT INTO STAGING.STG_SALESORDERHEADER (SalesOrderID,
    RevisionNumber, OrderDate, DueDate, ShipDate, Status,
    OnlineOrderFlag, SalesOrderNumber, PurchaseOrderNumber, AccountNumber,
    CustomerID, SalesPersonID, TerritoryID,
    BillToAddressID, ShipToAddressID, ShipMethodID,
    CreditCardID, CreditCardApprovalCode, CurrencyRateID,SubTotal,
    TaxAmt, Freight, TotalDue, CREATION_DATE
    )
    SELECT
    TRY_CAST(SalesOrderID AS INTEGER),
    TRY_CAST(RevisionNumber AS INTEGER),
    TRY_CAST(OrderDate AS DATE),
    TRY_CAST(DueDate AS DATE),
    TRY_CAST(ShipDate AS DATE),
    Status,
    TRY_CAST(OnlineOrderFlag AS INTEGER),
    SalesOrderNumber,
    PurchaseOrderNumber,
    AccountNumber,
    TRY_CAST(CustomerID AS INTEGER),
    TRY_CAST(SalesPersonID AS INTEGER),
    TRY_CAST(TerritoryID AS INTEGER),
    TRY_CAST(BillToAddressID AS INTEGER),
    TRY_CAST(ShipToAddressID AS INTEGER),
    TRY_CAST(ShipMethodID AS INTEGER),
    TRY_CAST(CreditCardID AS INTEGER),
    CreditCardApprovalCode,
    TRY_CAST(CurrencyRateID AS INTEGER),
    TRY_CAST(SubTotal AS FLOAT),
    TRY_CAST(TaxAmt AS FLOAT),
    TRY_CAST(Freight AS FLOAT),
    TRY_CAST(TotalDue AS FLOAT),
    TO_CHAR(CURRENT_TIMESTAMP(),'YYYY-MM-DD HH:MM:SS') AS CREATION_DATE
FROM RAW.SalesOrderHeader;

COMMIT;
RETURN 'OK - STG_SALESORDERHEADER CARGADO';
END;

-----------------------------------------------------------
--STG_SALESORDERDETAIL
-----------------------------------------------------------

CREATE OR REPLACE PROCEDURE STAGING.SP_LOAD_STG_SALESORDERDETAIL()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
TRUNCATE TABLE STAGING.STG_SALESORDERDETAIL;
    INSERT INTO STAGING.STG_SALESORDERDETAIL ( SalesOrderID,
    SalesOrderDetailID,CarrierTrackingNumber, OrderQty,
    ProductID, SpecialOfferID, UnitPrice, UnitPriceDiscount,
    LineTotal, CREATION_DATE
)
SELECT
    TRY_CAST(SalesOrderID AS INTEGER),
    TRY_CAST(SalesOrderDetailID AS INTEGER),
    CarrierTrackingNumber,
    TRY_CAST(OrderQty AS INTEGER),
    TRY_CAST(ProductID AS INTEGER),
    TRY_CAST(SpecialOfferID AS INTEGER),
    TRY_CAST(UnitPrice AS FLOAT),
    TRY_CAST(UnitPriceDiscount AS FLOAT),
    TRY_CAST(LineTotal AS FLOAT),
    TO_CHAR(CURRENT_TIMESTAMP(),'YYYY-MM-DD HH:MM:SS') AS CREATION_DATE
FROM RAW.SalesOrderDetail;

COMMIT;

RETURN 'OK - STG_SALESORDERDETAIL CARGADO';
END;

-----------------------------------------------------------
--STG_SALESORDER
-----------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_LOAD_STG_SALESORDER()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    TRUNCATE TABLE STAGING.STG_SALESORDER;
    INSERT INTO STAGING.STG_SALESORDER (	SALESORDERID,	SALESORDERDETAILID,
	ORDERDATE,	DUEDATE,	SHIPDATE,	STATUSID,	CUSTOMERID,	PRODUCTID,
	TAXAMT,	FREIGHT,	ORDERQTY,	UNITPRICE,	UNITPRICEDISCOUNT,	LINETOTAL,
	CREATION_DATE
)

        SELECT H.SALESORDERID, D.SALESORDERDETAILID,H.ORDERDATE, H.DUEDATE, H.SHIPDATE,  H.STATUS, H.CUSTOMERID, D.PRODUCTID, TAXAMT/COUNT(H.SALESORDERID) OVER(PARTITION BY H.SALESORDERID) AS PRO_TAXAMT, FREIGHT/COUNT(H.SALESORDERID) OVER(PARTITION BY H.SALESORDERID) AS PRO_FREIGHT, D.ORDERQTY, D.UNITPRICE, D.UNITPRICEDISCOUNT, D.LINETOTAL, TO_CHAR(CURRENT_TIMESTAMP(),'YYYY-MM-DD HH:MM:SS') AS CREATION_DATE
        
        FROM STAGING.STG_SALESORDERHEADER H 
        JOIN STAGING.STG_SALESORDERDETAIL D ON H.SALESORDERID = D.SALESORDERID ;

        COMMIT;

RETURN 'OK - STG_SALESORDER CARGADO';
END;

-----------------------------------------------------------
--STREAM
-----------------------------------------------------------
CREATE OR REPLACE STREAM STAGING.STM_STG_PRODUCT ON TABLE STAGING.STG_PRODUCT;
