USE DATABASE AW_PIPELINE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE ANALYTICS.DIM_CUSTOMER
(
CUSTOMERID INTEGER,
CUSTOMER_NAME VARCHAR(100),
REGION_NAME VARCHAR(100),
REGION_CODE VARCHAR(10),
CUSTOMER_TYPE VARCHAR(10),
CREATION_DATE DATETIME,
UPDATE_DATE DATETIME
);

CREATE OR REPLACE TABLE ANALYTICS.DIM_PRODUCT
(
PRODUCTID INTEGER,
PRODUCT_NUMBER VARCHAR(100),
NAME VARCHAR(100),
COLOR VARCHAR(100),
LISTPRICE NUMBER(15,4),
STANDARCOST NUMBER(15,4),
SUBCATEGORYNAME VARCHAR(100),
CATEGORYNAME VARCHAR(100),
CREATION_DATE DATETIME,
UPDATE_DATE DATETIME
);

CREATE OR REPLACE TABLE ANALYTICS.FACT_SALESORDER(
SALESORDERID INTEGER,
SALESORDERDETAILID INTEGER,
ORDERDATE DATETIME,
DUEDATE DATETIME,
SHIPDATE DATETIME,
STATUSID TINYINT,
CUSTOMERID INTEGER,
PRODUCTID INTEGER,
TAXAMT NUMBER(19,4),
FREIGHT NUMBER(19,4),
ORDERQTY  NUMBER(19,4),
UNITPRICE  NUMBER(19,4),
UNITPRICEDISCOUNT  NUMBER(19,4),
LINETOTAL  NUMBER(19,4),
CREATION_DATE DATETIME,
UPDATE_DATE DATETIME
);

CREATE OR REPLACE TABLE  ANALYTICS.DIM_STATUS(
STATUS_ID TINYINT,
STATUS_NAME VARCHAR(20)
);
