USE DATABASE AW_PIPELINE;
USE SCHEMA ANALYTICS;


CREATE OR REPLACE PROCEDURE ANALYTICS.SP_LOAD_DIM_CUSTOMER()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN   
    MERGE INTO ANALYTICS.DIM_CUSTOMER DM
    USING(
            SELECT CUSTOMERID
            , COALESCE(P.LastName ||' '|| P.FirstName, S.Name ) AS CUSTOMER_NAME
            , CASE WHEN C.PersonID IS NOT NULL THEN 'PERSONA'
                    WHEN C.StoreID IS NOT NULL THEN 'TIENDA' END CUSTOMER_TYPE
            , ST.Name AS REGION_NAME
            , ST.CountryRegionCode  AS REGION_CODE
            FROM STAGING.STG_CUSTOMER C
            LEFT JOIN STAGING.STG_PERSON P ON C.PersonID = P.BusinessEntityID 
            LEFT JOIN STAGING.STG_STORE S ON S.BusinessEntityID = C.StoreID 
            LEFT JOIN STAGING.STG_SALESTERRITORY ST ON ST.TerritoryID = C.TerritoryID
    ) AUX
    ON DM.CUSTOMERID = AUX.CUSTOMERID
    WHEN MATCHED THEN UPDATE
    SET DM.CUSTOMER_NAME = AUX.CUSTOMER_NAME, 
        DM.REGION_NAME = AUX.REGION_NAME,
        DM.REGION_CODE = AUX.REGION_CODE,
        DM.CUSTOMER_TYPE = AUX.CUSTOMER_TYPE,
        DM.UPDATE_DATE = TO_CHAR(CURRENT_TIMESTAMP(),'YYYY-MM-DD HH24:MI:SS')
    WHEN NOT MATCHED THEN
        INSERT(DM.CUSTOMERID, DM.CUSTOMER_NAME, DM.REGION_NAME, DM.REGION_CODE, DM.CUSTOMER_TYPE,DM.CREATION_DATE)
        VALUES (AUX.CUSTOMERID, AUX.CUSTOMER_NAME, AUX.REGION_NAME, AUX.REGION_CODE, AUX.CUSTOMER_TYPE, TO_CHAR(CURRENT_TIMESTAMP(),'YYYY-MM-DD HH24:MI:SS'));
        COMMIT;

        RETURN 'OK - DM_CUSTOMER';
END;


CREATE OR REPLACE PROCEDURE SP_LOAD_DIM_PRODUCT()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    MERGE INTO ANALYTICS.DIM_PRODUCT DM
    USING(
            SELECT * FROM STAGING.STM_STG_PRODUCT
            WHERE METADATA$ACTION = 'INSERT'
    ) AUX
    ON DM.PRODUCTID = AUX.PRODUCTID
    WHEN MATCHED THEN UPDATE
    SET DM.NAME = AUX.NAME, 
        DM.PRODUCT_NUMBER = AUX.PRODUCT_NUMBER,
        DM.COLOR = aUX.COLOR,
        DM.LISTPRICE = AUX.LISTPRICE,
        DM.STANDARCOST = AUX.STANDARCOST,
        DM.SUBCATEGORYNAME = AUX.SUBCATEGORYNAME,
        DM.CATEGORYNAME = AUX.CATEGORYNAME,
        DM.UPDATE_DATE = TO_CHAR(CURRENT_TIMESTAMP(),'YYYY-MM-DD HH24:MI:SS')
    WHEN NOT MATCHED THEN
        INSERT(DM.PRODUCTID, DM.PRODUCT_NUMBER, DM.COLOR, DM.LISTPRICE, DM.STANDARCOST, DM.SUBCATEGORYNAME,DM.CATEGORYNAME, DM.CREATION_DATE)
        VALUES (AUX.PRODUCTID, AUX.PRODUCT_NUMBER, AUX.COLOR, AUX.LISTPRICE, AUX.STANDARCOST, AUX.SUBCATEGORYNAME, AUX.CATEGORYNAME, TO_CHAR(CURRENT_TIMESTAMP(),'YYYY-MM-DD HH24:MI:SS'));
        COMMIT;
        RETURN 'OK - DM_PRODUCT';

END;    

CREATE OR REPLACE PROCEDURE SP_LOAD_FACT_SALESORDER()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    MERGE INTO ANALYTICS.FACT_SALESORDER FACT
    USING STAGING.STG_SALESORDER AUX
    ON FACT.SALESORDERID = AUX.SALESORDERID and FACT.SALESORDERDETAILID = AUX.SALESORDERDETAILID
    WHEN MATCHED THEN UPDATE
    SET 
        FACT.ORDERQTY = AUX.ORDERQTY,
        FACT.UNITPRICE = AUX.UNITPRICE,
        FACT.LINETOTAL = AUX.LINETOTAL,
        FACT.ORDERDATE = AUX.ORDERDATE,
        FACT.TAXAMT = AUX.TAXAMT,
        FACT.FREIGHT = AUX.FREIGHT,
        FACT.DUEDATE = AUX.DUEDATE,
        FACT.SHIPDATE = AUX.SHIPDATE,
        FACT.CUSTOMERID = AUX.CUSTOMERID,
        FACT.PRODUCTID = AUX.PRODUCTID,
        FACT.STATUSID = AUX.STATUSID,
        FACT.UPDATE_DATE = TO_CHAR(CURRENT_TIMESTAMP(),'YYYY-MM-DD HH24:MI:SS')
    WHEN NOT MATCHED THEN
       INSERT (FACT.SALESORDERID,FACT.SALESORDERDETAILID,FACT.PRODUCTID,FACT.ORDERQTY,FACT.UNITPRICE,FACT.LINETOTAL,FACT.ORDERDATE,FACT.TAXAMT,FACT.FREIGHT,FACT.DUEDATE,FACT.SHIPDATE,FACT.CUSTOMERID,FACT.STATUSID,FACT.CREATION_DATE)
        VALUES (AUX.SALESORDERID,AUX.SALESORDERDETAILID,AUX.PRODUCTID,AUX.ORDERQTY,AUX.UNITPRICE,AUX.LINETOTAL,AUX.ORDERDATE,AUX.TAXAMT,AUX.FREIGHT,AUX.DUEDATE,AUX.SHIPDATE,AUX.CUSTOMERID,AUX.STATUSID,TO_CHAR(CURRENT_TIMESTAMP(),'YYYY-MM-DD HH24:MI:SS'));
commit;
RETURN 'OK - FACT_SALESORDER CARGADO';
END;



