name: Deploy RAW to Snowflake

on:
  push:
    branches: [staging, main]   # agrega las ramas que quieras
    paths:
      - "RAW/**"             # solo corre si cambian estos archivos

env:
  REPO: aw_pipeline.orchestration.data_engineering_snowflake
  SQL_PATH: RAW              # carpeta del repo con tus .sql

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_CONNECTIONS_DATA_ENGINEERING_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DATA_ENGINEERING_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_DATA_ENGINEERING_SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install SnowflakeCLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"

      - name: Fetch del repo en Snowflake
        run: snow git fetch $REPO

      - name: Ejecutar scripts de la rama ${{ github.ref_name }}
        run: snow git execute "@$REPO/branches/${{ github.ref_name }}/$SQL_PATH/*.sql"
