name: Deploy RAW to Snowflake

on:
  push:
    branches: [staging, main]
    paths:
      - "RAW/**"

env:
  REPO: aw_pipeline.orchestration.data_engineering_snowflake
  SQL_PATH: RAW

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SnowflakeCLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"

      - name: Configure Snowflake Connection
        run: |
          snow connection set \
            --name data_engineering_snowflake \
            --account "${{ secrets.SNOWFLAKE_ACCOUNT }}" \
            --user "${{ secrets.SNOWFLAKE_USER }}" \
            --password "${{ secrets.SNOWFLAKE_PASSWORD }}"

      - name: Fetch del repo en Snowflake
        run: snow git fetch $REPO --connection data_engineering_snowflake

      - name: Ejecutar scripts de la rama ${{ github.ref_name }}
        run: snow git execute "@$REPO/branches/${{ github.ref_name }}/$SQL_PATH/*.sql" --connection data_engineering_snowflake
